export const ACTION_GET_RECEIPTS_STARTED = "GET_RECEIPTS_STARTED";
export const ACTION_GET_RECEIPTS_SUCCESS = "GET_RECEIPTS_SUCCESS";
export const ACTION_GET_RECEIPTS_FAILED = "GET_RECEIPTS_FAILED";

export const ACTION_CREATE_RECEIPT_STARTED = "CREATE_RECEIPT_STARTED";
export const ACTION_CREATE_RECEIPT_SUCCESS = "CREATE_RECEIPT_SUCCESS";