export const ACTION_GET_RECEIPTS_STARTED = "GET_RECEIPTS_STARTED";
export const ACTION_GET_RECEIPTS_SUCCESS = "GET_RECEIPTS_SUCCESS";
export const ACTION_GET_RECEIPTS_FAILED = "GET_RECEIPTS_FAILED";

export const ACTION_CREATE_RECEIPT_STARTED = "CREATE_RECEIPT_STARTED";
export const ACTION_CREATE_RECEIPT_SUCCESS = "CREATE_RECEIPT_SUCCESS";

// User
export const ACTION_GET_USER_STARTED = "GET_USER_STARTED";
export const ACTION_GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const ACTION_GET_USER_FAILED = "GET_USER_FAILED";

export const ACTION_CREATE_USER_STARTED = "CREATE_USER_STARTED";
export const ACTION_CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";

export const ACTION_LOGIN_STARTED = "LOGIN_STARTED";
export const ACTION_LOGIN_SUCCESS = "LOGIN_SUCCESS";